stages:
  - test
  - lmao
  - kek
  - lol

variables:
  ALLURE_LAUNCH_NAME: "${CI_PROJECT_NAME} - ${CI_COMMIT_SHORT_SHA}"
  ALLURE_LAUNCH_TAGS: "${CI_COMMIT_REF_NAME}, gitlab, demo, pytest, skip-live-doc, ignore"
  ALLURE_TESTPLAN_PATH: "testplan.json"
  ALLURE_ENDPOINT: "https://testing.testops.cloud"
  ALLURE_RESULTS: "allure-results"
  ALLURE_PROJECT_ID: 7804
  TESTS_ENDPOINT: "https://demo.testops.cloud"
  TESTS_BROWSER: "firefox"
  TESTS_BRANCH: ${CI_COMMIT_REF_NAME}
  ALLURE_TESTVARIABLE: "lets break this stuff up"


test1:
  image: python:3.9.1
  stage: lmao
  before_script :
    - wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O ./allurectl
    - chmod +x ./allurectl
    - pip install --upgrade pip setuptools wheel pytest allure-pytest
  script:
    - ./allurectl watch -- pytest test --alluredir=${ALLURE_RESULTS}
    - export $(./allurectl job-run env)
    - printenv
    - echo "${ALLURE_TESTVARIABLE}=============================================" 

test2:
  image: python:3.9.1
  stage: lol
  before_script:
    - wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O ./allurectl
    - chmod +x ./allurectl
    - pip install --upgrade pip setuptools wheel pytest allure-pytest
  script:
    - JR_UUID=$(openssl rand -hex 12)
    - ./allurectl watch --job-run-uid ${JR_UUID} -- pytest test --alluredir=${ALLURE_RESULTS}
    - export $(./allurectl job-run env)
    - printenv
    - echo "${ALLURE_TESTVARIABLE}=============================================" 

test3:
  image: python:3.9.1
  stage: kek
  before_script:
    - wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O ./allurectl
    - chmod +x ./allurectl
    - pip install --upgrade pip setuptools wheel pytest allure-pytest
  script:
    - JR_UUID=$(openssl rand -hex 12)
    - ./allurectl watch --job-run-uid ${JR_UUID} -- pytest test --alluredir=${ALLURE_RESULTS}
    - export $(./allurectl job-run env)
    - printenv
    - echo "${ALLURE_TESTVARIABLE}=============================================" 
  
  